import React, { useEffect } from 'react';

const CookiesPolicy = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="max-w-4xl mx-auto px-4 py-12 md:py-16">
            <h1 className="text-3xl md:text-4xl font-bold text-[#2D2D2D] mb-8">Cookies Policy</h1>

            <div className="prose prose-lg prose-indigo max-w-none text-gray-600 prose-a:text-[#3a307f] hover:prose-a:text-[#EA3934] prose-a:no-underline hover:prose-a:underline prose-a:transition-colors">
                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Introduction</h2>
                    <p>
                        Mortgage Finder respects your privacy, and we are committed to being transparent about the
                        technologies that we use. We provide this Cookies Policy to explain how and why cookies,
                        tracking pixels and other similar technologies may be stored on and accessed from your device
                        when you use or visit our websites (including <a href="https://www.mortgagefinder.ae">https://www.mortgagefinder.ae</a>) or our mobile
                        applications. This Cookies Policy should be read together with our Privacy Policy and Terms of
                        Use.
                    </p>
                    <p className="mt-4">
                        In this Policy, “Mortgage Finder”, “we” or “us” refers to Propertyfinder FZ-LLC and its
                        subsidiaries and affiliates.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Use of cookies</h2>
                    <p>
                        Like many websites, this website uses cookies (which may also be placed and read by third
                        party providers, including but not limited to Google Analytics), which are files that collect data
                        and store information on your hard drive. Cookies are used for purposes that include but are not
                        limited to allowing the user of such information or the website to identify account holders, track
                        new users, record session information, and generally to optimize your experience.
                    </p>
                    <p className="mt-4">
                        Most browsers accept cookies automatically but if you choose you can disable the cookies from
                        your browser. However, you may find that certain functions and features will not work as
                        intended on the services that you require.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Use of third party analytics and tracking pixels</h2>
                    <p>
                        This website uses third party analytics (“Third Party Analytics”). Third Party Analytics use
                        cookies and/or text files to analyse website traffic. Information generated by cookies with your
                        details (including your IP address) is transferred to servers operated by Third Party Analytics.
                        Third Party Analytics process this information to evaluate your use of this website, compile
                        reports about this website’s activity on our behalf, and deliver other related services regarding
                        website and Internet use. Third Party Analytics may also share this information with third parties
                        insofar as this is necessary or if these third parties process the information on behalf of them.
                    </p>
                    <p className="mt-4">
                        You may disable the cookies from your browser by adjusting your browser settings. However, in
                        this scenario, you may not be able to make full use of all the functions available on this website.
                    </p>
                    <p className="mt-4">
                        Third party tracking pixels are used on our website. This means that third parties may use
                        cookies, web beacons, and similar technologies to collect or receive information from our
                        website and elsewhere on the internet and use that information to provide measurement
                        services and target adverts. If you wish to opt out of the use of these tracking pixels please
                        adjust your browser settings.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Web server and application logs</h2>
                    <p>
                        Our servers automatically collect certain information to help us administer and protect our
                        services, analyse usage, and improve users’ experience. The information collected includes,
                        amongst others:
                    </p>
                    <ul className="list-disc pl-6 mt-4 space-y-2">
                        <li>IP address and browser type</li>
                        <li>Device information including Unique Device Identifier (UDID), MAC address, Identifier For Advertisers (IFA), and similar identifiers we or others may assign</li>
                        <li>Device operating system and other technical facts</li>
                        <li>Pages visited and content viewed, stored, and purchased</li>
                        <li>Information or text entered</li>
                        <li>Links and buttons clicked</li>
                        <li>URLs visited before and after you use our Services</li>
                    </ul>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Third party advertisers</h2>
                    <p>
                        We allow third party advertising networks to serve advertisements on our behalf. Third party
                        advertisers may place cookies on the browsers of visitors to its website(s) and may send its own
                        cookies to the visitors’ cookie file. The cookies will allow these third-party advertisers to apply
                        their personalized retargeting technology and to serve personalized banners; third party
                        advertisers may collect and use this data in accordance with all applicable laws and regulations
                        (including but not limited to laws governing privacy and data protection). Third party advertisers
                        will have their own privacy policies, and these will be available on their websites.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Interest-based advertising (IBA)</h2>
                    <p>
                        Interest-based advertising (IBA) allows us to deliver targeted advertising to users of our
                        services. IBA works by showing you advertisements that are based on the type of content you
                        access or read. For example, as you browse our services, one of the cookies placed on your
                        device will be an advertising cookie so we can better understand what sort of pages or content
                        you are interested in. The information collected about your device enables us to group you with
                        other devices that have shown similar interests. We can then display advertising to categories of
                        users that is based on common interests.
                    </p>
                    <p className="mt-4">
                        If you want to opt out of receiving interest-based advertising, it does not mean that you will no
                        longer receive advertising when you are using our services. It just means that we will not use
                        information collected about you for IBA and that any advertising you see will not be customized
                        or relevant to you. Please note that if you delete cookies, use a different device, or change web
                        browsers, you may need to opt out again.
                    </p>
                    <p className="mt-4">
                        Mobile devices have an identifier that gives companies the ability to serve targeted ads to a
                        specific mobile device. In many cases, you can turn off mobile device ad tracking or you can
                        reset the advertising identifier at any time within your mobile device privacy settings. You may
                        also choose to turn off location tracking on your mobile device. If you turn off ad tracking or
                        location tracking, we will no longer use information collected from your device’s advertising
                        identifier for the purposes of advertising. You may still see the same number of ads but they
                        may be less relevant because they will not be based on your interests.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">How do you contact us</h2>
                    <p>
                        If you have any questions relating to our Cookies Policy, please send an email to <a href="mailto:privacy@propertyfinder.ae">privacy@propertyfinder.ae</a> or a postal mail to the following address:
                    </p>
                    <p className="mt-4 font-semibold">
                        Data Privacy Officer, Propertyfinder FZ-LLC, Office 1505 in Shatha Tower, Dubai Media City,
                        Dubai, UAE.
                    </p>
                </section>
            </div>
        </div>
    );
};

export default CookiesPolicy;
